package com.example.demo.pojo;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.cretae_time
     *
     * @mbggenerated
     */
    private Date cretaeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.if_deleted
     *
     * @mbggenerated
     */
    private String ifDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.cretae_time
     *
     * @return the value of review.cretae_time
     *
     * @mbggenerated
     */
    public Date getCretaeTime() {
        return cretaeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.cretae_time
     *
     * @param cretaeTime the value for review.cretae_time
     *
     * @mbggenerated
     */
    public void setCretaeTime(Date cretaeTime) {
        this.cretaeTime = cretaeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.update_time
     *
     * @return the value of review.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.update_time
     *
     * @param updateTime the value for review.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.if_deleted
     *
     * @return the value of review.if_deleted
     *
     * @mbggenerated
     */
    public String getIfDeleted() {
        return ifDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.if_deleted
     *
     * @param ifDeleted the value for review.if_deleted
     *
     * @mbggenerated
     */
    public void setIfDeleted(String ifDeleted) {
        this.ifDeleted = ifDeleted == null ? null : ifDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.username
     *
     * @return the value of review.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.username
     *
     * @param username the value for review.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "Review{" +
                "id=" + id +
                ", cretaeTime=" + cretaeTime +
                ", updateTime=" + updateTime +
                ", ifDeleted='" + ifDeleted + '\'' +
                ", username='" + username + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}